{{- if .Values.secretsFromAkv.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "gooclaim-service.fullname" . }}-secret
  labels:
    {{- include "gooclaim-service.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.secretsFromAkv.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.secretsFromAkv.clusterSecretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ include "gooclaim-service.fullname" . }}-secret
    creationPolicy: Owner
  data:
    {{- range .Values.secretsFromAkv.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef }}
    {{- end }}
{{- end }}
