{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gooclaim-service.serviceAccountName" . }}
  labels:
    {{- include "gooclaim-service.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.serviceAccount.workloadIdentityClientId }}
    azure.workload.identity/client-id: {{ .Values.serviceAccount.workloadIdentityClientId | quote }}
    {{- end }}
{{- end }}
